namespace: todo-manager-namespace
buildId: 11
web:
  image:
    dockerHubId: borllor
    name: todo-manager
    tag: 0.1
    replicaCount: 2
  port: 80
sql:
  image:
    dockerHubId: microsoft
    name: mssql-server-linux
    tag: latest
    replicaCount: 1
  port: 1433

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}